import fs from 'node:fs';let h=fs.readFileSync('dist/index.html','utf8');
h=h.replace('<p class="eyebrow">GỬI TRAO TRƯỚC MÙA TRĂNG</p><h2>Món quà đã chọn.<br><em>Yêu thương sẵn sàng.</em></h2>','<p class="eyebrow">ƯU ĐÃI QUÀ TẶNG TRUNG THU</p><h2>Điền thông tin nhận ngay<br><em>quà tặng hoa lụa cao cấp.</em></h2>');
h=h.replace('placeholder="Số nhà, đường, phường/xã, tỉnh/thành phố"','placeholder="Số nhà, đường, phường/xã, quận/huyện, tỉnh/thành phố"');
h=h.replace('Xác nhận đặt hàng <span>↗</span>','XÁC NHẬN ĐẶT HÀNG NGAY <span>➜</span>');
h=h.replace('<article><img src="assets/helen.webp" alt="Nước hoa SR Helen 9ml"',`<article class="serum-step"><img src="assets/serum.webp" alt="Serum khử mùi SR Lilac Sage 10ml, ảnh chính thức từ Saras" width="800" height="800" loading="lazy"><div><span>03</span><h3>Khô thoáng<br>cùng Lilac Sage</h3><p>Serum giúp giảm mùi và mồ hôi vùng dưới cánh tay. Vệ sinh da trước khi dùng và sử dụng theo hướng dẫn của sản phẩm.</p><a class="routine-source" href="https://sarasbeauty.vn/san-pham/serum-khu-mui-cao-cap-sr-lilac-sage-10ml/" target="_blank" rel="noopener">Tìm hiểu serum Saras ↗</a></div></article><article class="perfume-step"><img src="assets/helen.webp" alt="Nước hoa SR Helen 9ml"`);
h=h.replace('<div><span>03</span><h3>Thêm hương','<div><span>04</span><h3>Thêm hương');
h=h.replace('<img id="document-image" alt="">','<div class="document-zoom-bar"><button type="button" id="zoom-document" aria-pressed="false">Phóng lớn 2×</button><span>Kéo ngang/dọc để đọc khi phóng lớn</span></div><div class="document-canvas"><img id="document-image" alt=""></div>');
fs.writeFileSync('dist/index.html',h);
for(const p of ['dist/app.js','google-apps-script/Code.gs']){let s=fs.readFileSync(p,'utf8');s=s.replaceAll('Bánh Lồng Đèn — Tứ Quý Ngọt Ngào','Bánh Lồng Đèn Bánh Dẻo Nhân “Tứ Quý Ngọt Ngào”').replaceAll('Bánh Lồng Đèn — Lục Vị Thơm Lừng','Bánh Lồng Đèn Bánh Nướng Nhân “Lục Vị Thơm Lừng”');s=s.replaceAll('Xác nhận đặt hàng <span>↗</span>','XÁC NHẬN ĐẶT HÀNG NGAY <span>➜</span>');fs.writeFileSync(p,s);}
fs.appendFileSync('dist/documents.js',`\nconst zoomDocument=document.querySelector('#zoom-document');zoomDocument.addEventListener('click',()=>{const on=zoomDocument.getAttribute('aria-pressed')!=='true';zoomDocument.setAttribute('aria-pressed',String(on));zoomDocument.textContent=on?'Thu nhỏ':'Phóng lớn 2×';docViewer.classList.toggle('is-zoomed',on);});docViewer.addEventListener('close',()=>{docViewer.classList.remove('is-zoomed');zoomDocument.setAttribute('aria-pressed','false');zoomDocument.textContent='Phóng lớn 2×';});\n`);
