import fs from 'node:fs';
let h=fs.readFileSync('dist/index.html','utf8');fs.copyFileSync('dist/index.html','index-before-slides.html');
h=h.replace(/<div class="order-selection"><fieldset>[\s\S]*?<\/fieldset><\/div>/,'');
h=h.replace('<div class="order-details"><fieldset>','<div class="order-details"><div class="compact-combo"><label for="order-combo">Chọn combo quà tặng</label><div id="combo-options"></div><div id="selected-combo-card" aria-live="polite"></div></div><fieldset>');
h=h.replace('<legend><span>02</span> Thông tin nhận hàng</legend>','<legend class="compact-legend">Thông tin nhận hàng</legend>');
h=h.replace('id="address" name="address" autocomplete="street-address" rows="3"','id="address" name="address" autocomplete="street-address" rows="2"');
h=h.replace(/<label for="note">([\s\S]*?)<\/textarea>/,'<details class="optional-note"><summary>Mùi hương & lời nhắn <span>(tùy chọn)</span></summary><label for="note">$1</textarea></details>');
h=h.replace(/<span>QUÀ TẶNG CỦA BẠN<\/span><h3 id="summary-name"><\/h3>/,'<h3 id="summary-name" class="visually-hidden"></h3>');
h=h.replace(/<p class="eyebrow">ƯU ĐÃI QUÀ TẶNG TRUNG THU<\/p><h2>[\s\S]*?<\/h2><p>Chọn combo và để lại thông tin. Saras sẽ liên hệ xác nhận đơn hàng và thời gian giao dự kiến.<\/p>/,'<p class="eyebrow">ƯU ĐÃI QUÀ TẶNG TRUNG THU</p><h2>Chọn quà. <em>Gửi yêu thương.</em></h2><p>Điền thông tin để Saras gọi xác nhận đơn.</p>');
h=h.replace(/<label for="quick-name">[\s\S]*?<label for="quick-combo">/,'<label for="quick-combo">');
h=h.replace('Điền thông tin, chọn món quà yêu thích và xem lại đơn trước khi gửi.','Chọn món quà bạn thích. Thông tin giao hàng sẽ được điền ở bước tiếp theo.');
h=h.replace('TIẾP TỤC XÁC NHẬN ĐƠN','CHỌN QUÀ NÀY — TIẾP TỤC');
for(const [cls,label] of [['ad-pain-grid','Tình huống chăm sóc'],['certificate-grid','Hồ sơ công bố'],['feature-grid','Combo quà tặng'],['brand-gallery queen-gallery','Bộ ảnh Á hậu'],['brand-benefits','Lợi ích Saras'],['scent-grid','Mùi hương Saras'],['routine-rows','Chăm sóc mỗi ngày'],['review-grid','Đánh giá sản phẩm']])h=h.replace(`class="${cls}"`,`class="${cls} mobile-slider" data-slider="${label}"`);
h=h.replace('<h2>Những lời chia sẻ<br><em>từ website Saras.</em></h2>','<h2>Khách hàng nói gì<br><em>về Saras Beauty?</em></h2>');
h=h.replace('Ba đánh giá công khai theo từng sản phẩm.<br>Nội dung và số sao được giữ nguyên từ nguồn.','Trải nghiệm về nước hoa và chăm sóc da.<br>Đánh giá theo từng sản phẩm trên sarasbeauty.vn.');
h=h.replaceAll('<span class="review-avatar" aria-hidden="true">TH</span>','<img class="review-avatar" src="assets/avatar-th.svg" alt="Avatar chữ cái TH" width="48" height="48">');
h=h.replace('<link rel="stylesheet" href="mobile-first.css">','<link rel="stylesheet" href="mobile-first.css"><link rel="stylesheet" href="compact-mobile.css">');
h=h.replace('</body>','<script src="sliders.js" defer></script></body>');fs.writeFileSync('dist/index.html',h);
let js=fs.readFileSync('dist/app.js','utf8');
const start=js.indexOf("const root=document.querySelector('#combo-options')");const end=js.indexOf("const form=document.querySelector('#order-form')");
js=js.slice(0,start)+`const root=document.querySelector('#combo-options');
const comboSelect=document.createElement('select');comboSelect.id='order-combo';comboSelect.name='combo';comboSelect.required=true;root.append(comboSelect);
const SHORT_NAMES={'le':'1 nước hoa Nam / Nữ','dau-do':'Đậu Đỏ · 1 Nam + 1 Nữ','ngot-ngao':'Đôi Ngọt Ngào · 2 Nữ','men-li':'Men Lì · 2 Nam','song-hy':'Song Hỷ · 2 Nam + 2 Nữ','vuot-nang':'Vượt Nắng · Bộ skincare','trung-muoi':'Trứng Muối · 4 sản phẩm','thap-cam':'Thập Cẩm · 6 sản phẩm','tu-quy':'Tứ Quý · 4 nước hoa Nữ','luc-vi':'Lục Vị · 6 nước hoa'};
for(const c of COMBOS){const option=document.createElement('option');option.value=c.id;option.textContent=SHORT_NAMES[c.id]+' — '+money(c.price);comboSelect.append(option);}comboSelect.value='song-hy';
`+js.slice(end);
js=js.replace("document.querySelector('#total').textContent=money(c.price+c.ship);}","document.querySelector('#total').textContent=money(c.price+c.ship);const img=['vuot-nang','trung-muoi','thap-cam'].includes(c.id)?'albatross.webp':'gift.webp';document.querySelector('#selected-combo-card').innerHTML=`<img src=\"assets/${img}\" alt=\"Ảnh sản phẩm minh họa\" width=\"64\" height=\"64\"><div><strong>${c.name}</strong><span>${c.detail}</span><small>${c.gift}</small></div>`;}");
fs.writeFileSync('dist/app.js',js);
fs.writeFileSync('dist/quick-order.js',`'use strict';
const quickSelect=document.querySelector('#quick-combo');
COMBOS.forEach(c=>{const option=document.createElement('option');option.value=c.id;option.textContent=SHORT_NAMES[c.id]+' — '+money(c.price);quickSelect.append(option);});quickSelect.value='dau-do';
function updateQuickTotal(){const c=COMBOS.find(c=>c.id===quickSelect.value);document.querySelector('#quick-total').textContent=money(c.price+c.ship);}
quickSelect.addEventListener('change',updateQuickTotal);updateQuickTotal();
document.querySelector('#quick-form').addEventListener('submit',e=>{e.preventDefault();form.elements.combo.value=quickSelect.value;updateSummary();document.querySelector('#dat-hang').scrollIntoView({behavior:'instant'});form.elements.customer.focus({preventScroll:true});});
`);
