import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync('dist/index.html','utf8');const attrs=[...html.matchAll(/(?:src|href)="([^"#][^"]*)"/g)].map(m=>m[1]).filter(p=>!/^https?:|^tel:|^mailto:|^data:/.test(p));for(const p of attrs)assert(fs.existsSync('dist/'+p),`Missing ${p}`);const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));for(const m of html.matchAll(/href="#([^"]+)"/g))assert(ids.has(m[1]),`Broken anchor ${m[1]}`);
const rows=[];let rateLimited=false;const sheet={getLastRow:()=>rows.length+1,getRange:()=>({createTextFinder:id=>({matchEntireCell:()=>({findNext:()=>rows.some(r=>r[0]===id)})})}),appendRow:r=>rows.push(r)};
const context=vm.createContext({ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})},LockService:{getScriptLock:()=>({tryLock:()=>true,hasLock:()=>true,releaseLock:()=>{}})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet}),flush:()=>{}},CacheService:{getScriptCache:()=>({get:()=>rateLimited?'1':null,put:()=>{rateLimited=true;}})},Utilities:{DigestAlgorithm:{SHA_256:1},computeDigest:()=>[1,2,3],formatDate:()=> '2026-09-16 14:00:00'},console});vm.runInContext(fs.readFileSync('google-apps-script/Code.gs','utf8'),context);
const data={requestId:'12345678-1234-1234-1234-123456789012',combo:'le',customer:'=UNTRUSTED()',phone:'0900000000',address:'Địa chỉ TEST',note:'@note',consent:true};const submit=d=>context.doPost({postData:{contents:JSON.stringify(d)}});assert.equal(submit({...data,consent:false}).ok,false);assert.equal(rows.length,0);assert.equal(submit({...data,phone:'123'}).ok,false);assert.equal(submit({...data,combo:'invalid'}).ok,false);assert.equal(submit(data).ok,true);assert.equal(rows.length,1);assert.equal(rows[0][9],219000);assert.equal(rows[0][2],"'=UNTRUSTED()");assert.equal(submit(data).ok,true);assert.equal(rows.length,1);assert.equal(submit({...data,requestId:'22345678-1234-1234-1234-123456789012'}).ok,false);
rateLimited=false;assert.equal(submit({...data,requestId:'32345678-1234-1234-1234-123456789012',combo:'song-hy'}).ok,true);assert.equal(rows[1][9],559000);assert.equal(rows[1][8],0);console.log('PASS: local assets, anchor targets, input validation, authoritative prices, shipping, duplicate retry, rate limit, formula escaping. No real orders sent.');

